### PR TITLE
example gist of config files

### PR DESCRIPTION
**Pull request by johndpope**

### CODE REVIEW

**Comment by xiaoyao1991** [comment]
The sample config may introduce extra confusion to users because that config is configured to use another connector. I'm thinking maybe we should write the example config more in detail in either README, or in a `doc` folder and link there in the README

**Comment by xiaoyao1991** [comment]
Also, the file tree following the line you changed seem to be broken. You can see it by click the review button on the markdown file on Github. Github markdown style is really weird.

**Comment by johndpope** [comment]
I agree with adding confusion - I don't have much time to play around with this stuff. I may get more time next week. I do like these first steps in gist using wget. 

I installed presto using their readme / then using brew - in the end - it would have been easier with a bit of spoon feeding.
screen shot 2017-08-07 at 11 22 48 am

I suggest creating a fresh gist include a RUNME.sh that could prompt users to install presto.
let me see.

**Comment by johndpope** [comment]
something like this https://gist.github.com/johndpope/142af754bf7cc78f77509ee10aa44bc9

**Pull request closed without merging**
